name: publish-release

on:
  release:
    types:
      - released

jobs:
  call-publish-pypi:
    uses: ./.github/workflows/publish-pypi.yaml
    with:
      pypi_repository_url: https://upload.pypi.org/legacy/
    secrets:
      pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
